name: M3U tester

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'  # Runs at 22:30 UTC
    - cron: '0 7 * * *'    # Runs at 07:00 UTC

jobs:
  m3u-tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4
      - name: Debug GitHub Secrets (safe)
        run: |
          echo "Username length: ${#BITBUCKET_USERNAME}"
          echo "Password length: ${#BITBUCKET_APP_PASSWORD}"
        env:
          BITBUCKET_USERNAME: ${{ secrets.BB_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BB_TOKEN }}
      - name: Clone source repo
        run: |
          git config --global credential.helper ""
          REPO_URL="https://bitbucket.org/SaadBenbouzid/m3u.git"
          git clone https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@${REPO_URL#https://}
        env:
          BITBUCKET_USERNAME: ${{ secrets.BB_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BB_TOKEN }}
      - name: Clone stalker repo
        run: |
          git clone https://github.com/Macadoshis/stalker-to-m3u.git
      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Prepare m3u files
        run: |
          cd m3u
          chmod u+x *.sh
          ./restore.sh > /dev/null
          ./reset.sh > /dev/null
          echo "`ls *.m3u | wc -l` files restored"
        env:
          PGP_PWD: ${{ secrets.PGP_PWD }}
      - name: Prepare stalker environment
        run: |
          cd stalker-to-m3u
          node -v
          npm -v
          npm config set loglevel info
          chmod u+x configure
          chmod u+x tools/m3u-tester
          ./configure
          sudo add-apt-repository ppa:savoury1/ffmpeg4
          sudo apt update
          sudo apt install ffmpeg
          rm -rf ffmpeg ffprobe
          ln -s "$(which ffmpeg)" ./ffmpeg
          ln -s "$(which ffprobe)" ./ffprobe
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h
      - name: Run M3U tester
        run: |
          cd stalker-to-m3u
          # do not output progression
          tools/./m3u-tester --m3uLocation="../m3u" --minSuccess=3 --maxFailures=50 --renamePrefix="_" --renameOnFailure="true" --threadsCount=10 --streamTester=ffmpeg > /dev/null
      - name: Update M3U results
        run: |
          cd m3u
          echo "\u274C `ls _iptv-*.m3u | wc -l` ITV files UNhealthy"
          echo "\u274C `ls _vod-*.m3u | wc -l` VOD files UNhealthy"
          echo "\u274C `ls _series-*.m3u | wc -l` SERIES files UNhealthy"
          echo "\u2705 `ls iptv-*.m3u | wc -l` ITV files healthy"
          echo "\u2705 `ls vod-*.m3u | wc -l` VOD files healthy"
          echo "\u2705 `ls series-*.m3u | wc -l` SERIES files healthy"
          ./copy.sh