name: M3U tester
run-name: M3U tester (${{ inputs.streamTester || 'ffmpeg' }})

on:
  workflow_call:
    inputs:
      streamTester:
        description: 'M3U stream tester'
        type: string
        required: true
      m3u:
        description: 'M3U file'
        type: string
        required: false
        default: ''
    secrets:
      BB_USERNAME:
        required: true
      BB_TOKEN:
        required: true
      PGP_PWD:
        required: true
      GIT_USERNAME:
        required: true
      GIT_USEREMAIL:
        required: true
      STALKER_REPO_PAT:
        required: true
      SOURCE_REPO:
        required: true

  workflow_dispatch:
    inputs:
      m3u:
        description: 'M3U file'
        required: false
        default: ''
      minSuccess:
        description: 'M3U tester min success'
        required: true
        default: 30
      maxFailures:
        description: 'M3U tester max failures'
        required: true
        default: 50
      streamTester:
        description: 'M3U stream tester'
        type: choice
        options:
          - ffmpeg
          - http
        required: true
        default: ffmpeg

  schedule:
    - cron: '0 12 * * *'   # Runs at 13:00 UTC / 09:00 EDT
    - cron: '00 16 * * *'  # Runs at 17:00 UTC / 13:00 EDT
    - cron: '30 00 * * *'  # Runs at 01:30 UTC / 21:30 EDT

concurrency:
  group: tester-queue
  cancel-in-progress: false

env:
  TESTER_REPORT_FILE: tester-failed.json

jobs:
  m3u-tester:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone source repo
        run: |
          git config --global credential.helper ""
          REPO_URL="https://bitbucket.org/SaadBenbouzid/m3u.git"
          git clone https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@${REPO_URL#https://}
        env:
          BITBUCKET_USERNAME: ${{ secrets.BB_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.BB_TOKEN }}
      - name: Clone repo
        run: |
          git clone https://x-access-token:${{ secrets.STALKER_REPO_PAT }}@github.com/${{ secrets.SOURCE_REPO }} repo
      - name: Configure NODE
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Restore m3u files
        run: |
          cd m3u
          chmod u+x *.sh
          ./restore.sh > /dev/null
          echo "`ls *.m3u | wc -l` files restored"
        env:
          PGP_PWD: ${{ secrets.PGP_PWD }}
      - name: Update summary
        run: |
          cd m3u
          echo "## CURRENT content" >> $GITHUB_STEP_SUMMARY
          echo -e "| Type    | \u274C #                   | \u2705 #                  |" >> $GITHUB_STEP_SUMMARY
          echo -e "|---------|----------------------------|---------------------------|" >> $GITHUB_STEP_SUMMARY
          echo -e "| IPTV    | `ls _iptv-*.m3u | wc -l || echo "0"`   | `ls iptv-*.m3u | wc -l || echo "0"`   |" >> $GITHUB_STEP_SUMMARY
          echo -e "| VOD     | `ls _vod-*.m3u | wc -l || echo "0"`    | `ls vod-*.m3u | wc -l || echo "0"`    |" >> $GITHUB_STEP_SUMMARY
          echo -e "| SERIES  | `ls _series-*.m3u | wc -l || echo "0"` | `ls series-*.m3u | wc -l || echo "0"` |" >> $GITHUB_STEP_SUMMARY
      - name: Prepare m3u files
        run: |
          cd m3u
          if [[ -z "${{ inputs.m3u }}" ]]; then
            echo "Resetting m3u..."
            ./reset.sh > /dev/null
          elif [[ "${{ inputs.m3u }}" == *.m3u ]]; then
            echo "NOT resetting m3u..."
            mv "_${{ inputs.m3u }}" ${{ inputs.m3u }} && echo "${{ inputs.m3u }} has been reset" || echo "No _${{ inputs.m3u }} to reset"
          elif [[ "${{ inputs.m3u }}" == *"-*"* ]]; then
            generatorKind="${{ inputs.m3u }}"
            generatorKind="${generatorKind%%-*}"
            echo "M3U pattern detected, resetting by generator kind: ${generatorKind}"
            ./reset.sh "${generatorKind}" > /dev/null
          else
            echo "Ignoring reset..."
          fi

      - name: Prepare environment
        run: |
          cd repo
          node -v
          npm -v
          npm config set loglevel info
          chmod u+x configure
          chmod u+x tools/m3u-tester
          # ./configure
          npm install
          # sudo add-apt-repository ppa:savoury1/ffmpeg4
          sudo apt update
          sudo apt install ffmpeg
          rm -rf ffmpeg ffprobe
          ln -s "$(which ffmpeg)" ./ffmpeg
          ln -s "$(which ffprobe)" ./ffprobe
          # sudo fallocate -l 4G /swapfile
          # sudo chmod 600 /swapfile
          # sudo mkswap /swapfile
          # sudo swapon /swapfile
          # free -h
      - name: Run M3U tester
        run: |
          cd repo
          # do not output progression
          tools/./m3u-tester --m3uLocation="../m3u/${{ inputs.m3u }}" --minSuccess=${{ inputs.minSuccess || 30 }} --maxFailures=${{ inputs.maxFailures || 50 }} --renamePrefix="_" --renameOnFailure="true" --archiveOnExceededFailure="true" --maxDaysBeforeArchive=7 --threadsCount=10 --streamTester=${{ inputs.streamTester || 'ffmpeg' }}  > /dev/null 2>&1
          mv ./${{ env.TESTER_REPORT_FILE }} ../m3u || echo "No ${{ env.TESTER_REPORT_FILE }} file to move"
      - name: Update summary
        run: |
          cd m3u
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## RESULT content" >> $GITHUB_STEP_SUMMARY
          echo -e "| Type    | \u274C #                   | \u2705 #                  |" >> $GITHUB_STEP_SUMMARY
          echo -e "|---------|----------------------------|---------------------------|" >> $GITHUB_STEP_SUMMARY
          echo -e "| IPTV    | `ls _iptv-*.m3u | wc -l || echo "0"`   | `ls iptv-*.m3u | wc -l || echo "0"`   |" >> $GITHUB_STEP_SUMMARY
          echo -e "| VOD     | `ls _vod-*.m3u | wc -l || echo "0"`    | `ls vod-*.m3u | wc -l || echo "0"`    |" >> $GITHUB_STEP_SUMMARY
          echo -e "| SERIES  | `ls _series-*.m3u | wc -l || echo "0"` | `ls series-*.m3u | wc -l || echo "0"` |" >> $GITHUB_STEP_SUMMARY
      - name: Push M3U results
        run: |
          cd m3u
          git config user.email "${{ secrets.GIT_USEREMAIL }}"
          git config user.name "${{ secrets.GIT_USERNAME }}"
          ./copy.sh > /dev/null
        env:
          PGP_PWD: ${{ secrets.PGP_PWD }}
